config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  authenticated :user do
    root to: "welcome#index", as: "auth_root"
  end  

  root to: redirect("/users/sign_in")
  
  resources :whowas_searches, only: [:index, :create]
  resources :lockouts, only: [:index] do
    collection do
      get 'search'  # for links
      post 'search' # for form
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lockout.rb
class Lockout < ApplicationRecord
  scope :in_last, -> (range) { where(timestamp: (Time.now - range)..Time.now) }
  scope :by_newest, -> { order("timestamp DESC") }
  scope :for_user, -> (username) { where(username: username) }
    
  scope :top_users, lambda { |num|
    group("username").order("count_username DESC").count("username").take(num)
  }

  scope :top_hosts, lambda { |num|
    group("host").order("count_host DESC").count("host").take(num)
  }  

  def formatted_timestamp
    self.timestamp.strftime("%Y/%m/%e %I:%M %p")
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :ldap_authenticatable, :timeoutable, :trackable

  validates :username, presence: true
end

app/models/whowas_search.rb
class WhowasSearch
  include ActiveModel::Model
  
  attr_accessor :timestamp, :ip, :port
  attr_accessor :username, :results
  attr_accessor :error
  
  def search!
    search = Whowas.search(input)
    self.results = search[:results]
    self.username = search[:input][:username]
    self.error = search[:error]
  rescue StandardError => e
    self.error = e.inspect
  end
  
  private
  
  def input
    {
      timestamp: Time.parse(timestamp).to_s,
      ip: ip,
      port: port.to_s
    }.delete_if { |key, value| (value.nil? || value.empty? rescue false) }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from DeviseLdapAuthenticatable::LdapException do |exception|
    render :text => exception, :status => 500
  end
  protect_from_forgery with: :exception
end

app/controllers/lockouts_controller.rb
class LockoutsController < ApplicationController
  before_action :authenticate_user!
    
  def index
    @lockout = Lockout.new
    @lockouts = Lockout.in_last(24.hours).by_newest
    @top_lockouts = Lockout.in_last(72.hours).top_users(5)
  end
  
  def search
    @username = params[:lockout][:username]
    @lockout = Lockout.new
    @lockouts = Lockout.for_user(@username).by_newest
    @top_hosts = Lockout.for_user(@username).top_hosts(5)
  end 
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    render template: "index.html.haml"
  end
end

app/controllers/whowas_searches_controller.rb
class WhowasSearchesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @search ||= WhowasSearch.new 
    respond_to do |format|
      format.js
      format.html
    end    
  end
  
  def create
    @search = WhowasSearch.new(whowas_search_params)
    
    Rails.logger.tagged("INFOSEC-ECHO") {
      Rails.logger.info "#{current_user.username} initiated a Whowas search." 
    }    
    
    @search.search!
    
    render :index, search: @search
  end
  
  def whowas_search_params
    params.require(:whowas_search).permit(:ip, :port, :timestamp)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
  # :nocov:
  def humanize_error(error)
    case error.to_s
    when /no time information/
      "Could not understand timestamp format.  Please try again.  An example of a known valid format is \"August 25, 2016 10:00 AM EST\"."
    when /IPAddr::InvalidAddressError/
      "IP address is missing or invalid."
    when /Invalid input for Whowas::Firewall/
      "Invalid input for the first search query.  Note: a valid port is required for this IP address."
    else
      "An unknown error occured.  Please send an email to #{ENV["EMAIL"]} with the following message: #{error}."
    end
  end
  # :nocov:
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_css_overrides.html.erb
<% if Rails.env.test? %>
  <style type="text/css">
    * {
      transition-property: none !important;
    }
  </style>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/layouts/_header.html.haml
%section.header-wrapper{role: "header"}
  .header-container
    = link_to root_path, class: "branding" do
      .title echo v2
    - if current_user
      %a{class: "nav-toggle"}
        Menu
      %nav{class: "closed"}
        %ul
          %li.header-user
            = link_to "Sign out", destroy_user_session_path, method: :delete

app/views/layouts/_nav.html.haml
%section.nav-wrapper{role: "nav"}
  .nav-container
    - if page == "lockouts"
      .nav-box-small.selected
        .nav-icon-small.selected
          = fa_icon "lock"
        Lockouts
    - else        
      = link_to lockouts_path do
        .nav-box-small
          .nav-icon-small
            = fa_icon "lock"
          Lockouts
          
    - if page == "whowas"
      .nav-box-small.selected
        .nav-icon-small.selected 
          = fa_icon "user"
        Whowas
    - else  
      = link_to whowas_searches_path do                   
        .nav-box-small
          .nav-icon-small
            = fa_icon "user"
          Whowas

app/views/layouts/application.html.haml
!!! 5
%html{lang: "en"}
  %head
    %title Echo
  
    = javascript_include_tag "application"
    = stylesheet_link_tag "application"
    = csrf_meta_tags
    %meta{name: "viewport", content: "width=device-width,initial-scale=1"}

  %body  
    = render "layouts/header"

    = render "shared/flashes"

    %section.content
      - if content_for(:subheader)
        = yield(:subheader)
      = yield

app/views/lockouts/_lockouts.html.haml
.lockouts-search-results-js
  %h2 Lockouts - Past 24 hours
  
  %table#lockouts-table
    %thead
      %th Timestamp
      %th Username
      %th Host
    %tbody
      - @lockouts.each do |result|
        %tr
          %td
            = result.formatted_timestamp
          %td
            = link_to result.username, search_lockouts_path(lockout: {username: result.username})
          %td
            = result.host

app/views/lockouts/_results.html.haml
.lockouts-search-results-js
  %h2
    Lockouts for 
    = @username
    
  %table#lockouts-results-table
    %thead
      %th Timestamp
      %th Host
    %tbody
      - @lockouts.each do |result|
        %tr
          %td
            = result.formatted_timestamp
          %td
            = result.host

app/views/lockouts/_search_form.html.haml
.lockouts-search-form
  = semantic_form_for @lockout, url: search_lockouts_path, method: :get do |form|
    = form.inputs do
      = form.input :username, label: "Tufts Username"
    = form.actions do
      = form.action :submit, label: "Search"

app/views/lockouts/index.html.haml
- content_for :subheader do
  = render "layouts/nav", page: "lockouts"


%section#lockouts-search.flex-box
  %h2.flex-title
    Lockouts
  
  .sidebar  
    = render "search_form"
  
    .sidebar-container
      %h2 Top Lockouts in Past 72 Hours
      - @top_lockouts.each do |lockout|
        .sidebar-row
          .sidebar-row-left
            = link_to lockout[0], search_lockouts_path(lockout: {username: lockout[0]})
          .sidebar-row-right
            = lockout[1].to_s

  .lockouts-search-results
    #lockouts-search-results-content
      = render "lockouts"

app/views/lockouts/search.html.haml
- content_for :subheader do
  %header
    .page-title


%section#lockouts-search.flex-box
  %h2.flex-title
    Lockouts
    
  .sidebar
    = render "search_form"
  
    .sidebar-container
      %h2 
        Top Hosts for 
        = @username
        
      - @top_hosts.each do |host|
        .sidebar-row
          .sidebar-row-left
            = link_to host[0], search_lockouts_path(lockout: {username: @username}, queries2: {search: host[0]})
          .sidebar-row-right
            = host[1]
            
  .lockouts-search-results
    #lockouts-search-results-content
      = render "results"
      
    = link_to "<< Back to index", lockouts_path

app/views/shared/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/shared/_spinner.html.haml
.spinner-container
  .spinner
    .bounce1
    .bounce2
    .bounce3

app/views/whowas_searches/_results.html.haml
.whowas-search-results-js
  - if search.error
    .whowas-search-errors
      %h2 Errors
      = humanize_error(search.error)
            
  - else
    %h2 Username
    %p
      = search.username || "No username found."
    
    %h2 Raw logs
    - if search.results
      %p
        .whowas-results-table
          - search.results.each do |log|
            - log.each do |key, value|
              .whowas-results-label
                = key
              .whowas-results-log
                = value

app/views/whowas_searches/index.html.haml
- content_for :subheader do
  = render "layouts/nav", page: "whowas"

%section#whowas-search.flex-box
  %h2.flex-title
    Search WhoWas

  .whowas-search-form
    = semantic_form_for @search, remote: true do |form|
      = form.inputs do
        = form.input :ip, label: "IP Address"
        = form.input :port, label: "Port", hint: "Optional; required for secure wireless."
        = form.input :timestamp, label: "Timestamp", hint: "Accepts most date and time formats, e.g. 9/1/2016 10:00 AM.  Timezone is Eastern unless specified."
      = form.actions do
        = form.action :submit, label: "Search"

  .whowas-search-results
    #whowas-search-spinner
      = render "shared/spinner"
        
    #whowas-search-results-content.loading-content
    
  - if @search.username
    = @search.username
    

app/views/whowas_searches/index.js.haml
:plain
  $("#whowas-search-results-content").html("#{escape_javascript(render(partial: "results", locals: {search: @search}))}")